### ISSUE TITLE
Кривые длинные названия

### ISSUE THREAD

**Issue by Shemplo** [Shemplo/Study-courses#1]

**Comment by egormkn** [comment]
👍

**Comment by Shemplo** [comment]
В проекте [SD - 4. Tasks service](https://github.com/Shemplo/Study-courses/tree/master/Software%20design/SD%20-%204.%20Tasks%20Service) есть баг с отображением данных, если ввести длинное имя списка или описание задания (в частности, если ввести одно слово без пробелов)
